"""
ANSI escape sequences and utils.
"""

import re

ANSI_BEEP = "\07"
ANSI_ESCAPE = "\033"
ANSI_NORMAL = "\033[0m"

ANSI_UNDERLINE = "\033[4m"
ANSI_HILITE = "\033[1m"
ANSI_BLINK = "\033[5m"
ANSI_INVERSE = "\033[7m"
ANSI_INV_HILITE = "\033[1;7m"
ANSI_INV_BLINK = "\033[7;5m"
ANSI_BLINK_HILITE = "\033[1;5m"
ANSI_INV_BLINK_HILITE = "\033[1;5;7m"

# Foreground colors
ANSI_BLACK = "\033[30m"
ANSI_HI_BLACK = ANSI_HILITE + ANSI_BLACK
ANSI_RED = "\033[31m"
ANSI_HI_RED = ANSI_HILITE + ANSI_RED
ANSI_GREEN = "\033[32m"
ANSI_HI_GREEN = ANSI_HILITE + ANSI_GREEN
ANSI_YELLOW = "\033[33m"
ANSI_HI_YELLOW = ANSI_HILITE + ANSI_YELLOW
ANSI_BLUE = "\033[34m"
ANSI_HI_BLUE = ANSI_HILITE + ANSI_BLUE
ANSI_MAGENTA = "\033[35m"
ANSI_HI_MAGENTA = ANSI_HILITE + ANSI_MAGENTA
ANSI_CYAN = "\033[36m"
ANSI_HI_CYAN = ANSI_HILITE + ANSI_CYAN
ANSI_WHITE = "\033[37m"
ANSI_HI_WHITE = ANSI_HILITE + ANSI_WHITE

# Background colors
ANSI_BACK_BLACK = "\033[40m"
ANSI_BACK_RED = "\033[41m"
ANSI_BACK_GREEN = "\033[42m"
ANSI_BACK_YELLOW = "\033[43m"
ANSI_BACK_BLUE = "\033[44m"
ANSI_BACK_MAGENTA = "\033[45m"
ANSI_BACK_CYAN = "\033[46m"
ANSI_BACK_WHITE = "\033[47m"

# Formatting Characters
ANSI_RETURN = "\r\n"
ANSI_TAB = "\t"
ANSI_SPACE = " "


RE_ANSI_ESCAPES = re.compile(r'\x1b[^m]*m')

def remove_ansi_escape_seqs(colored_text):
    return RE_ANSI_ESCAPES.sub('', colored_text)